/* Modelo Físico - Reset Completo */
DROP DATABASE IF EXISTS PRESENCA_ALUNOS;
CREATE DATABASE PRESENCA_ALUNOS;
USE PRESENCA_ALUNOS;

-- Remove as tabelas antigas se elas existirem (ordem importa por causa das chaves estrangeiras)
DROP TABLE IF EXISTS PROFESSOR_ATIVIDADE_LECIONA;
DROP TABLE IF EXISTS ALUNOS_PRESENTES_PARTICIPA;
DROP TABLE IF EXISTS ATIVIDADE;
DROP TABLE IF EXISTS PROFESSOR;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS PESSOA_CADASTRAR;

CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT PRIMARY KEY,
    NOME_DEPARTAMENTO VARCHAR(100) NOT NULL
);

CREATE TABLE PESSOA_CADASTRAR (
    ID_PESSOA INT NOT NULL,
    ID_CADASTRO INT NOT NULL,
    NOME_PESSOA VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NULL,
    TIPO VARCHAR(50) NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    OBSERVACAO VARCHAR(255),
    PRIMARY KEY (ID_PESSOA, ID_CADASTRO)
);

CREATE TABLE PROFESSOR (
    ID_PROFESSOR INT PRIMARY KEY,
    NOME_PROFESSOR VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NULL,
    FK_DEPARTAMENTO_ID INT,
    CONSTRAINT FK_PROFESSOR_DEPARTAMENTO FOREIGN KEY (FK_DEPARTAMENTO_ID)
        REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
);

CREATE TABLE ATIVIDADE (
    ID_ATIVIDADE INT PRIMARY KEY,
    DATA_ATIVIDADE DATE NOT NULL,
    TIPO_ATIVIDADE VARCHAR(100) NOT NULL,
    STATUS_ATIVIDADE VARCHAR(20) NOT NULL DEFAULT 'Agendada',
    DATA_INICIO DATETIME NULL,
    DATA_FIM DATETIME NULL,
    CONSTRAINT CK_STATUS_ATIVIDADE CHECK (STATUS_ATIVIDADE IN ('Agendada', 'Em andamento', 'Encerrada')),
    CONSTRAINT CK_PERIODO_ATIVIDADE CHECK (DATA_FIM IS NULL OR DATA_INICIO IS NULL OR DATA_FIM >= DATA_INICIO)
);

CREATE TABLE ALUNOS_PRESENTES_PARTICIPA (
    ID_ALUNOS_PRESENTES INT PRIMARY KEY,
    STATUS_PRESENCA VARCHAR(20) NOT NULL,
    FK_PESSOA_CADASTRAR_ID_PESSOA INT NOT NULL,
    FK_PESSOA_CADASTRAR_ID_CADASTRO INT NOT NULL,
    FK_ATIVIDADE_ID_ATIVIDADE INT NOT NULL,
    CONSTRAINT CK_STATUS_PRESENCA CHECK (STATUS_PRESENCA IN ('Presente', 'Ausente')),
    CONSTRAINT UQ_PRESENCA_ALUNO_ATIVIDADE UNIQUE (
        FK_PESSOA_CADASTRAR_ID_PESSOA,
        FK_PESSOA_CADASTRAR_ID_CADASTRO,
        FK_ATIVIDADE_ID_ATIVIDADE
    )
);

CREATE TABLE PROFESSOR_ATIVIDADE_LECIONA (
    ID_PROFESSOR_ATIVIDADE INT PRIMARY KEY,
    FK_ATIVIDADE_ID_ATIVIDADE INT NOT NULL,
    FK_PROFESSOR_ID_PROFESSOR INT NOT NULL,
    CONSTRAINT UQ_PROFESSOR_ATIVIDADE UNIQUE (
        FK_ATIVIDADE_ID_ATIVIDADE,
        FK_PROFESSOR_ID_PROFESSOR
    )
);
 
-- Chaves Estrangeiras da tabela de Presença
ALTER TABLE ALUNOS_PRESENTES_PARTICIPA ADD CONSTRAINT FK_ALUNOS_PRESENTES_PARTICIPA_2
    FOREIGN KEY (FK_PESSOA_CADASTRAR_ID_PESSOA, FK_PESSOA_CADASTRAR_ID_CADASTRO)
    REFERENCES PESSOA_CADASTRAR (ID_PESSOA, ID_CADASTRO);
 
ALTER TABLE ALUNOS_PRESENTES_PARTICIPA ADD CONSTRAINT FK_ALUNOS_PRESENTES_PARTICIPA_3
    FOREIGN KEY (FK_ATIVIDADE_ID_ATIVIDADE)
    REFERENCES ATIVIDADE (ID_ATIVIDADE);
 
-- Chaves Estrangeiras da tabela de Alocação de Professor
ALTER TABLE PROFESSOR_ATIVIDADE_LECIONA ADD CONSTRAINT FK_PROFESSOR_ATIVIDADE_LECIONA_2
    FOREIGN KEY (FK_ATIVIDADE_ID_ATIVIDADE)
    REFERENCES ATIVIDADE (ID_ATIVIDADE);
 
ALTER TABLE PROFESSOR_ATIVIDADE_LECIONA ADD CONSTRAINT FK_PROFESSOR_ATIVIDADE_LECIONA_3
    FOREIGN KEY (FK_PROFESSOR_ID_PROFESSOR)
    REFERENCES PROFESSOR (ID_PROFESSOR);

-- Consulta resumida por atividade.
SELECT
    A.ID_ATIVIDADE AS id_atividade,
    A.DATA_ATIVIDADE AS data,
    A.TIPO_ATIVIDADE AS atividade,
    A.STATUS_ATIVIDADE AS status,
    A.DATA_INICIO AS data_inicio,
    A.DATA_FIM AS data_fim,
    COALESCE(GROUP_CONCAT(DISTINCT PR.NOME_PROFESSOR SEPARATOR ', '), 'Não alocado') AS professores,
    COALESCE(GROUP_CONCAT(DISTINCT CASE WHEN APP.STATUS_PRESENCA = 'Presente' THEN P.NOME_PESSOA END SEPARATOR ', '), 'Nenhum aluno presente') AS alunos_presentes,
    COUNT(DISTINCT CASE WHEN APP.STATUS_PRESENCA = 'Presente' THEN CONCAT(APP.FK_PESSOA_CADASTRAR_ID_PESSOA, '-', APP.FK_PESSOA_CADASTRAR_ID_CADASTRO) END) AS total_presentes,
    COUNT(DISTINCT CASE WHEN APP.STATUS_PRESENCA = 'Ausente' THEN CONCAT(APP.FK_PESSOA_CADASTRAR_ID_PESSOA, '-', APP.FK_PESSOA_CADASTRAR_ID_CADASTRO) END) AS total_ausentes
FROM ATIVIDADE A
LEFT JOIN ALUNOS_PRESENTES_PARTICIPA APP
    ON A.ID_ATIVIDADE = APP.FK_ATIVIDADE_ID_ATIVIDADE
LEFT JOIN PESSOA_CADASTRAR P
    ON P.ID_PESSOA = APP.FK_PESSOA_CADASTRAR_ID_PESSOA
   AND P.ID_CADASTRO = APP.FK_PESSOA_CADASTRAR_ID_CADASTRO
LEFT JOIN PROFESSOR_ATIVIDADE_LECIONA PAL
    ON A.ID_ATIVIDADE = PAL.FK_ATIVIDADE_ID_ATIVIDADE
LEFT JOIN PROFESSOR PR
    ON PR.ID_PROFESSOR = PAL.FK_PROFESSOR_ID_PROFESSOR
GROUP BY A.ID_ATIVIDADE, A.DATA_ATIVIDADE, A.TIPO_ATIVIDADE,
         A.STATUS_ATIVIDADE, A.DATA_INICIO, A.DATA_FIM
ORDER BY A.DATA_ATIVIDADE DESC;